//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace testConsoleApplication1.HSFEntityWebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HSFEntityWebServiceSoap", Namespace="http://hyperion.com/hsf/hsfwebservices/")]
    public partial class HSFEntityWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OpenEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnumAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnumScenariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnumTimePeriodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnumMeasuresOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnumCustomDimensionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnumCustomMembersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEntityDataCellsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetEntityDataCellsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportExtendedAnalyticsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEntityLockInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReleaseEntityLockOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetScenarioInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetForecastInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetScenarioInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HSFEntityWebService() {
            //this.Url = global::testConsoleApplication1.Properties.Settings.Default.testConsoleApplication1_HSFEntityWebService_HSFEntityWebService;
            this.Url = "http://oa8050.us.oracle.com:12000/HSFWebServices/HSFEntityWebService.asmx";
            //this.Url = "http://localhost:8001/HSFWebServices/HSFEntityWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public HSFEntityWebService(String abc)
        {
            //this.Url = global::testConsoleApplication1.Properties.Settings.Default.testConsoleApplication1_HSFEntityWebService_HSFEntityWebService;
            //this.Url = "http://oa8050.us.oracle.com:12000/HSFWebServices/HSFEntityWebService.asmx";
            this.Url = "http://localhost:8001/HSFWebServices/HSFEntityWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OpenEntityCompletedEventHandler OpenEntityCompleted;
        
        /// <remarks/>
        public event CloseEntityCompletedEventHandler CloseEntityCompleted;
        
        /// <remarks/>
        public event EnumAccountsCompletedEventHandler EnumAccountsCompleted;
        
        /// <remarks/>
        public event EnumScenariosCompletedEventHandler EnumScenariosCompleted;
        
        /// <remarks/>
        public event EnumTimePeriodsCompletedEventHandler EnumTimePeriodsCompleted;
        
        /// <remarks/>
        public event EnumMeasuresCompletedEventHandler EnumMeasuresCompleted;
        
        /// <remarks/>
        public event EnumCustomDimensionsCompletedEventHandler EnumCustomDimensionsCompleted;
        
        /// <remarks/>
        public event EnumCustomMembersCompletedEventHandler EnumCustomMembersCompleted;
        
        /// <remarks/>
        public event GetEntityDataCellsCompletedEventHandler GetEntityDataCellsCompleted;
        
        /// <remarks/>
        public event SetEntityDataCellsCompletedEventHandler SetEntityDataCellsCompleted;
        
        /// <remarks/>
        public event CalculateCompletedEventHandler CalculateCompleted;
        
        /// <remarks/>
        public event ExportExtendedAnalyticsCompletedEventHandler ExportExtendedAnalyticsCompleted;
        
        /// <remarks/>
        public event CreateEntityCompletedEventHandler CreateEntityCompleted;
        
        /// <remarks/>
        public event GetEntityLockInfoCompletedEventHandler GetEntityLockInfoCompleted;
        
        /// <remarks/>
        public event ReleaseEntityLockCompletedEventHandler ReleaseEntityLockCompleted;
        
        /// <remarks/>
        public event GetScenarioInfoCompletedEventHandler GetScenarioInfoCompleted;
        
        /// <remarks/>
        public event SetForecastInfoCompletedEventHandler SetForecastInfoCompleted;
        
        /// <remarks/>
        public event SetScenarioInfoCompletedEventHandler SetScenarioInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/OpenEntity", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet OpenEntity(string sessionID, string entity, bool checkOut) {
            object[] results = this.Invoke("OpenEntity", new object[] {
                        sessionID,
                        entity,
                        checkOut});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OpenEntityAsync(string sessionID, string entity, bool checkOut) {
            this.OpenEntityAsync(sessionID, entity, checkOut, null);
        }
        
        /// <remarks/>
        public void OpenEntityAsync(string sessionID, string entity, bool checkOut, object userState) {
            if ((this.OpenEntityOperationCompleted == null)) {
                this.OpenEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpenEntityOperationCompleted);
            }
            this.InvokeAsync("OpenEntity", new object[] {
                        sessionID,
                        entity,
                        checkOut}, this.OpenEntityOperationCompleted, userState);
        }
        
        private void OnOpenEntityOperationCompleted(object arg) {
            if ((this.OpenEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpenEntityCompleted(this, new OpenEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/CloseEntity", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CloseEntity(string sessionID, bool checkIn, bool releaseLock) {
            this.Invoke("CloseEntity", new object[] {
                        sessionID,
                        checkIn,
                        releaseLock});
        }
        
        /// <remarks/>
        public void CloseEntityAsync(string sessionID, bool checkIn, bool releaseLock) {
            this.CloseEntityAsync(sessionID, checkIn, releaseLock, null);
        }
        
        /// <remarks/>
        public void CloseEntityAsync(string sessionID, bool checkIn, bool releaseLock, object userState) {
            if ((this.CloseEntityOperationCompleted == null)) {
                this.CloseEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseEntityOperationCompleted);
            }
            this.InvokeAsync("CloseEntity", new object[] {
                        sessionID,
                        checkIn,
                        releaseLock}, this.CloseEntityOperationCompleted, userState);
        }
        
        private void OnCloseEntityOperationCompleted(object arg) {
            if ((this.CloseEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseEntityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/EnumAccounts", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EnumAccounts(string sessionID) {
            object[] results = this.Invoke("EnumAccounts", new object[] {
                        sessionID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EnumAccountsAsync(string sessionID) {
            this.EnumAccountsAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void EnumAccountsAsync(string sessionID, object userState) {
            if ((this.EnumAccountsOperationCompleted == null)) {
                this.EnumAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnumAccountsOperationCompleted);
            }
            this.InvokeAsync("EnumAccounts", new object[] {
                        sessionID}, this.EnumAccountsOperationCompleted, userState);
        }
        
        private void OnEnumAccountsOperationCompleted(object arg) {
            if ((this.EnumAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnumAccountsCompleted(this, new EnumAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/EnumScenarios", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EnumScenarios(string sessionID) {
            object[] results = this.Invoke("EnumScenarios", new object[] {
                        sessionID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EnumScenariosAsync(string sessionID) {
            this.EnumScenariosAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void EnumScenariosAsync(string sessionID, object userState) {
            if ((this.EnumScenariosOperationCompleted == null)) {
                this.EnumScenariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnumScenariosOperationCompleted);
            }
            this.InvokeAsync("EnumScenarios", new object[] {
                        sessionID}, this.EnumScenariosOperationCompleted, userState);
        }
        
        private void OnEnumScenariosOperationCompleted(object arg) {
            if ((this.EnumScenariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnumScenariosCompleted(this, new EnumScenariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/EnumTimePeriods", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EnumTimePeriods(string sessionID) {
            object[] results = this.Invoke("EnumTimePeriods", new object[] {
                        sessionID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EnumTimePeriodsAsync(string sessionID) {
            this.EnumTimePeriodsAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void EnumTimePeriodsAsync(string sessionID, object userState) {
            if ((this.EnumTimePeriodsOperationCompleted == null)) {
                this.EnumTimePeriodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnumTimePeriodsOperationCompleted);
            }
            this.InvokeAsync("EnumTimePeriods", new object[] {
                        sessionID}, this.EnumTimePeriodsOperationCompleted, userState);
        }
        
        private void OnEnumTimePeriodsOperationCompleted(object arg) {
            if ((this.EnumTimePeriodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnumTimePeriodsCompleted(this, new EnumTimePeriodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/EnumMeasures", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EnumMeasures(string sessionID) {
            object[] results = this.Invoke("EnumMeasures", new object[] {
                        sessionID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EnumMeasuresAsync(string sessionID) {
            this.EnumMeasuresAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void EnumMeasuresAsync(string sessionID, object userState) {
            if ((this.EnumMeasuresOperationCompleted == null)) {
                this.EnumMeasuresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnumMeasuresOperationCompleted);
            }
            this.InvokeAsync("EnumMeasures", new object[] {
                        sessionID}, this.EnumMeasuresOperationCompleted, userState);
        }
        
        private void OnEnumMeasuresOperationCompleted(object arg) {
            if ((this.EnumMeasuresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnumMeasuresCompleted(this, new EnumMeasuresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/EnumCustomDimensions", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EnumCustomDimensions(string sessionID) {
            object[] results = this.Invoke("EnumCustomDimensions", new object[] {
                        sessionID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EnumCustomDimensionsAsync(string sessionID) {
            this.EnumCustomDimensionsAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void EnumCustomDimensionsAsync(string sessionID, object userState) {
            if ((this.EnumCustomDimensionsOperationCompleted == null)) {
                this.EnumCustomDimensionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnumCustomDimensionsOperationCompleted);
            }
            this.InvokeAsync("EnumCustomDimensions", new object[] {
                        sessionID}, this.EnumCustomDimensionsOperationCompleted, userState);
        }
        
        private void OnEnumCustomDimensionsOperationCompleted(object arg) {
            if ((this.EnumCustomDimensionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnumCustomDimensionsCompleted(this, new EnumCustomDimensionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/EnumCustomMembers", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EnumCustomMembers(string sessionID, string dimension, string parent, string action) {
            object[] results = this.Invoke("EnumCustomMembers", new object[] {
                        sessionID,
                        dimension,
                        parent,
                        action});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EnumCustomMembersAsync(string sessionID, string dimension, string parent, string action) {
            this.EnumCustomMembersAsync(sessionID, dimension, parent, action, null);
        }
        
        /// <remarks/>
        public void EnumCustomMembersAsync(string sessionID, string dimension, string parent, string action, object userState) {
            if ((this.EnumCustomMembersOperationCompleted == null)) {
                this.EnumCustomMembersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnumCustomMembersOperationCompleted);
            }
            this.InvokeAsync("EnumCustomMembers", new object[] {
                        sessionID,
                        dimension,
                        parent,
                        action}, this.EnumCustomMembersOperationCompleted, userState);
        }
        
        private void OnEnumCustomMembersOperationCompleted(object arg) {
            if ((this.EnumCustomMembersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnumCustomMembersCompleted(this, new EnumCustomMembersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/GetEntityDataCells", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEntityDataCells(string sessionID, System.Data.DataSet dataCellLocators) {
            object abc = new object[] {sessionID,dataCellLocators};
           
            Console.WriteLine(abc.ToString());
            object[] results = this.Invoke("GetEntityDataCells", new object[] {
                        sessionID,
                        dataCellLocators});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetEntityDataCellsAsync(string sessionID, System.Data.DataSet dataCellLocators) {
            this.GetEntityDataCellsAsync(sessionID, dataCellLocators, null);
        }
        
        /// <remarks/>
        public void GetEntityDataCellsAsync(string sessionID, System.Data.DataSet dataCellLocators, object userState) {
            if ((this.GetEntityDataCellsOperationCompleted == null)) {
                this.GetEntityDataCellsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEntityDataCellsOperationCompleted);
            }
            this.InvokeAsync("GetEntityDataCells", new object[] {
                        sessionID,
                        dataCellLocators}, this.GetEntityDataCellsOperationCompleted, userState);
        }
        
        private void OnGetEntityDataCellsOperationCompleted(object arg) {
            if ((this.GetEntityDataCellsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEntityDataCellsCompleted(this, new GetEntityDataCellsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/SetEntityDataCells", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SetEntityDataCells(string sessionID, System.Data.DataSet dataCellInfos, string source) {
            object[] results = this.Invoke("SetEntityDataCells", new object[] {
                        sessionID,
                        dataCellInfos,
                        source});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SetEntityDataCellsAsync(string sessionID, System.Data.DataSet dataCellInfos, string source) {
            this.SetEntityDataCellsAsync(sessionID, dataCellInfos, source, null);
        }
        
        /// <remarks/>
        public void SetEntityDataCellsAsync(string sessionID, System.Data.DataSet dataCellInfos, string source, object userState) {
            if ((this.SetEntityDataCellsOperationCompleted == null)) {
                this.SetEntityDataCellsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetEntityDataCellsOperationCompleted);
            }
            this.InvokeAsync("SetEntityDataCells", new object[] {
                        sessionID,
                        dataCellInfos,
                        source}, this.SetEntityDataCellsOperationCompleted, userState);
        }
        
        private void OnSetEntityDataCellsOperationCompleted(object arg) {
            if ((this.SetEntityDataCellsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetEntityDataCellsCompleted(this, new SetEntityDataCellsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/Calculate", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Calculate(string sessionID, bool normalCalc, bool reverseCalc) {
            object[] results = this.Invoke("Calculate", new object[] {
                        sessionID,
                        normalCalc,
                        reverseCalc});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateAsync(string sessionID, bool normalCalc, bool reverseCalc) {
            this.CalculateAsync(sessionID, normalCalc, reverseCalc, null);
        }
        
        /// <remarks/>
        public void CalculateAsync(string sessionID, bool normalCalc, bool reverseCalc, object userState) {
            if ((this.CalculateOperationCompleted == null)) {
                this.CalculateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateOperationCompleted);
            }
            this.InvokeAsync("Calculate", new object[] {
                        sessionID,
                        normalCalc,
                        reverseCalc}, this.CalculateOperationCompleted, userState);
        }
        
        private void OnCalculateOperationCompleted(object arg) {
            if ((this.CalculateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateCompleted(this, new CalculateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/ExportExtendedAnalytics", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExportExtendedAnalytics(string sessionID, string analysisVersion) {
            this.Invoke("ExportExtendedAnalytics", new object[] {
                        sessionID,
                        analysisVersion});
        }
        
        /// <remarks/>
        public void ExportExtendedAnalyticsAsync(string sessionID, string analysisVersion) {
            this.ExportExtendedAnalyticsAsync(sessionID, analysisVersion, null);
        }
        
        /// <remarks/>
        public void ExportExtendedAnalyticsAsync(string sessionID, string analysisVersion, object userState) {
            if ((this.ExportExtendedAnalyticsOperationCompleted == null)) {
                this.ExportExtendedAnalyticsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportExtendedAnalyticsOperationCompleted);
            }
            this.InvokeAsync("ExportExtendedAnalytics", new object[] {
                        sessionID,
                        analysisVersion}, this.ExportExtendedAnalyticsOperationCompleted, userState);
        }
        
        private void OnExportExtendedAnalyticsOperationCompleted(object arg) {
            if ((this.ExportExtendedAnalyticsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportExtendedAnalyticsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/CreateEntity", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateEntity(string sessionID, string newEntity, string baseEntity, string rootEntity, string parentEntity, bool keepData) {
            this.Invoke("CreateEntity", new object[] {
                        sessionID,
                        newEntity,
                        baseEntity,
                        rootEntity,
                        parentEntity,
                        keepData});
        }
        
        /// <remarks/>
        public void CreateEntityAsync(string sessionID, string newEntity, string baseEntity, string rootEntity, string parentEntity, bool keepData) {
            this.CreateEntityAsync(sessionID, newEntity, baseEntity, rootEntity, parentEntity, keepData, null);
        }
        
        /// <remarks/>
        public void CreateEntityAsync(string sessionID, string newEntity, string baseEntity, string rootEntity, string parentEntity, bool keepData, object userState) {
            if ((this.CreateEntityOperationCompleted == null)) {
                this.CreateEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEntityOperationCompleted);
            }
            this.InvokeAsync("CreateEntity", new object[] {
                        sessionID,
                        newEntity,
                        baseEntity,
                        rootEntity,
                        parentEntity,
                        keepData}, this.CreateEntityOperationCompleted, userState);
        }
        
        private void OnCreateEntityOperationCompleted(object arg) {
            if ((this.CreateEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEntityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/GetEntityLockInfo", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEntityLockInfo(string sessionID, string entity) {
            object[] results = this.Invoke("GetEntityLockInfo", new object[] {
                        sessionID,
                        entity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEntityLockInfoAsync(string sessionID, string entity) {
            this.GetEntityLockInfoAsync(sessionID, entity, null);
        }
        
        /// <remarks/>
        public void GetEntityLockInfoAsync(string sessionID, string entity, object userState) {
            if ((this.GetEntityLockInfoOperationCompleted == null)) {
                this.GetEntityLockInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEntityLockInfoOperationCompleted);
            }
            this.InvokeAsync("GetEntityLockInfo", new object[] {
                        sessionID,
                        entity}, this.GetEntityLockInfoOperationCompleted, userState);
        }
        
        private void OnGetEntityLockInfoOperationCompleted(object arg) {
            if ((this.GetEntityLockInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEntityLockInfoCompleted(this, new GetEntityLockInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/ReleaseEntityLock", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ReleaseEntityLock(string sessionID, string entity) {
            object[] results = this.Invoke("ReleaseEntityLock", new object[] {
                        sessionID,
                        entity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReleaseEntityLockAsync(string sessionID, string entity) {
            this.ReleaseEntityLockAsync(sessionID, entity, null);
        }
        
        /// <remarks/>
        public void ReleaseEntityLockAsync(string sessionID, string entity, object userState) {
            if ((this.ReleaseEntityLockOperationCompleted == null)) {
                this.ReleaseEntityLockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReleaseEntityLockOperationCompleted);
            }
            this.InvokeAsync("ReleaseEntityLock", new object[] {
                        sessionID,
                        entity}, this.ReleaseEntityLockOperationCompleted, userState);
        }
        
        private void OnReleaseEntityLockOperationCompleted(object arg) {
            if ((this.ReleaseEntityLockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReleaseEntityLockCompleted(this, new ReleaseEntityLockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/GetScenarioInfo", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetScenarioInfo(string sessionID) {
            object[] results = this.Invoke("GetScenarioInfo", new object[] {
                        sessionID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetScenarioInfoAsync(string sessionID) {
            this.GetScenarioInfoAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void GetScenarioInfoAsync(string sessionID, object userState) {
            if ((this.GetScenarioInfoOperationCompleted == null)) {
                this.GetScenarioInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScenarioInfoOperationCompleted);
            }
            this.InvokeAsync("GetScenarioInfo", new object[] {
                        sessionID}, this.GetScenarioInfoOperationCompleted, userState);
        }
        
        private void OnGetScenarioInfoOperationCompleted(object arg) {
            if ((this.GetScenarioInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScenarioInfoCompleted(this, new GetScenarioInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/SetForecastInfo", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetForecastInfo(string sessionID, string entity, string scenario, string account, string xmlStr) {
            this.Invoke("SetForecastInfo", new object[] {
                        sessionID,
                        entity,
                        scenario,
                        account,
                        xmlStr});
        }
        
        /// <remarks/>
        public void SetForecastInfoAsync(string sessionID, string entity, string scenario, string account, string xmlStr) {
            this.SetForecastInfoAsync(sessionID, entity, scenario, account, xmlStr, null);
        }
        
        /// <remarks/>
        public void SetForecastInfoAsync(string sessionID, string entity, string scenario, string account, string xmlStr, object userState) {
            if ((this.SetForecastInfoOperationCompleted == null)) {
                this.SetForecastInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetForecastInfoOperationCompleted);
            }
            this.InvokeAsync("SetForecastInfo", new object[] {
                        sessionID,
                        entity,
                        scenario,
                        account,
                        xmlStr}, this.SetForecastInfoOperationCompleted, userState);
        }
        
        private void OnSetForecastInfoOperationCompleted(object arg) {
            if ((this.SetForecastInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetForecastInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://hyperion.com/hsf/hsfwebservices/SetScenarioInfo", RequestNamespace="http://hyperion.com/hsf/hsfwebservices/", ResponseNamespace="http://hyperion.com/hsf/hsfwebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetScenarioInfo(string sessionID, string scenarioInfo) {
            this.Invoke("SetScenarioInfo", new object[] {
                        sessionID,
                        scenarioInfo});
        }
        
        /// <remarks/>
        public void SetScenarioInfoAsync(string sessionID, string scenarioInfo) {
            this.SetScenarioInfoAsync(sessionID, scenarioInfo, null);
        }
        
        /// <remarks/>
        public void SetScenarioInfoAsync(string sessionID, string scenarioInfo, object userState) {
            if ((this.SetScenarioInfoOperationCompleted == null)) {
                this.SetScenarioInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetScenarioInfoOperationCompleted);
            }
            this.InvokeAsync("SetScenarioInfo", new object[] {
                        sessionID,
                        scenarioInfo}, this.SetScenarioInfoOperationCompleted, userState);
        }
        
        private void OnSetScenarioInfoOperationCompleted(object arg) {
            if ((this.SetScenarioInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetScenarioInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void OpenEntityCompletedEventHandler(object sender, OpenEntityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpenEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpenEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CloseEntityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnumAccountsCompletedEventHandler(object sender, EnumAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnumAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnumAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnumScenariosCompletedEventHandler(object sender, EnumScenariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnumScenariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnumScenariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnumTimePeriodsCompletedEventHandler(object sender, EnumTimePeriodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnumTimePeriodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnumTimePeriodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnumMeasuresCompletedEventHandler(object sender, EnumMeasuresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnumMeasuresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnumMeasuresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnumCustomDimensionsCompletedEventHandler(object sender, EnumCustomDimensionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnumCustomDimensionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnumCustomDimensionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EnumCustomMembersCompletedEventHandler(object sender, EnumCustomMembersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnumCustomMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnumCustomMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetEntityDataCellsCompletedEventHandler(object sender, GetEntityDataCellsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEntityDataCellsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEntityDataCellsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SetEntityDataCellsCompletedEventHandler(object sender, SetEntityDataCellsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetEntityDataCellsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetEntityDataCellsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CalculateCompletedEventHandler(object sender, CalculateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ExportExtendedAnalyticsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CreateEntityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetEntityLockInfoCompletedEventHandler(object sender, GetEntityLockInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEntityLockInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEntityLockInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ReleaseEntityLockCompletedEventHandler(object sender, ReleaseEntityLockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReleaseEntityLockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReleaseEntityLockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetScenarioInfoCompletedEventHandler(object sender, GetScenarioInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScenarioInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScenarioInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SetForecastInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SetScenarioInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591